name: Auto Update when upstream releases
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Fetch release version
        id: upstream
        run: |
          echo ::set-output name=release_tag::$(curl "https://api.github.com/repos/PKief/vscode-material-icon-theme/commits?per_page=100" \
          | jq '.[] | .commit.message' \
          | grep -m 1 -oP '^"Release\s+\K(\d+\.\d+\.\d+)')
          echo ::set-output name=current_tag::$(<upstream.version)

      - name: Build new release
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        # TODO: enable build step. Only useful when this cuts a release/auto update stores
        # run: npm install && npm version patch --no-git-tag-version && npm run build
        # TODO: remove this useless bumper when above is enabled
        run: npm version patch --no-git-tag-version 

      - name: Update current upstream version
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        run: echo ${{ steps.upstream.outputs.release_tag}} > upstream.version

      - name: Create pull request
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update extension with upstream version ${{ steps.upstream.outputs.release_tag}}
          title: '[auto] Update extension with upstream version ${{ steps.upstream.outputs.release_tag}}'
          branch: upstream-updates
          body: |
            Bumps patch version and rebuilds extension for upload to stores.

            Triggered by [Upstream][1] release

            Auto generated by github action.

            [1]: https://github.com/PKief/vscode-material-icon-theme

# TODO: either create release with zips or directly update stores
